# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: setup angular project
    #install global project dependencies.
    before: | 
      npm install -g @azure/static-web-apps-cli
    # downloading dependencies or compiling source. runs during prebuild
    init: | 
      cd angular-app
      npm i
      npm start
    #start development server etc
    command: | 
      swa start http://localhost:4200 --api-location api


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200
    onOpen: open-preview
